# Generated by Django 4.0.4 on 2022-04-30 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='style',
            field=models.ManyToManyField(blank=True, null=True, to='art.style'),
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='technique',
            field=models.ManyToManyField(blank=True, null=True, to='art.technique'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='technique',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
