# Generated by Django 4.0.4 on 2024-01-11 14:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_alter_artpiece_style_alter_artpiece_technique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
