# Generated by Django 4.0.4 on 2022-04-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_alter_artpiece_liked_by_usernewstimestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usernewstimestamp',
            old_name='product',
            new_name='news',
        ),
        migrations.AlterField(
            model_name='usernewstimestamp',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time Stamp'),
        ),
    ]
