# Generated by Django 4.0.4 on 2022-04-26 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art', '0003_event_user_news_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artpiece',
            name='likes',
        ),
        migrations.AddField(
            model_name='artpiece',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
