# Generated by Django 4.0.4 on 2022-04-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_rename_product_usernewstimestamp_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='type',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
