# Generated by Django 4.0.4 on 2022-04-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_artpiece_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='medium_used',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
