# Generated by Django 4.0.4 on 2022-04-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_artpiece_liked_by_remove_artpiece_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='technique',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
