# Generated by Django 4.0.4 on 2022-04-27 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_style_photo_technique_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_free_entrance',
        ),
    ]
