# Generated by Django 4.0.4 on 2022-04-27 22:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_remove_event_is_free_entrance'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
