# Generated by Django 4.0.4 on 2022-04-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0008_event_photo_news_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.URLField(verbose_name='Photo URL'),
        ),
    ]
