# Generated by Django 4.0.4 on 2022-04-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arthubuser',
            name='is_artist',
        ),
        migrations.AlterField(
            model_name='regularprofile',
            name='is_artist',
            field=models.CharField(choices=[('Artist', 'Artist'), ('Art-enthusiast', 'Art-enthusiast')], default=False, max_length=14),
        ),
    ]
