# Generated by Django 4.0.4 on 2022-04-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_arthubuser_is_artist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.arthubuser',),
        ),
        migrations.CreateModel(
            name='ArtModUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.arthubuser',),
        ),
        migrations.CreateModel(
            name='RegularUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.arthubuser',),
        ),
        migrations.RemoveField(
            model_name='regularprofile',
            name='is_artist',
        ),
        migrations.AddField(
            model_name='arthubuser',
            name='type',
            field=models.CharField(choices=[('ARTIST', 'Artist'), ('REGULAR_USER', 'Regular User'), ('ART_MOD', 'Art Mod')], default='REGULAR_USER', max_length=50),
        ),
    ]
