# Generated by Django 4.0.4 on 2022-04-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_arthubuser_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arthubuser',
            name='type',
            field=models.CharField(choices=[('ARTIST', 'Artist'), ('REGULAR_USER', 'Regular User'), ('ART_MOD', 'Art Mod')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
