# Generated by Django 4.0.4 on 2024-01-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arthubuser',
            name='type',
            field=models.CharField(choices=[('ARTIST', 'Artist'), ('REGULAR_USER', 'Regular User'), ('ART_MOD', 'Art Mod')], default='REGULAR_USER', max_length=50),
        ),
    ]
