# Generated by Django 4.0.4 on 2022-04-26 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_regularprofile_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegularProfile',
            new_name='UserProfile',
        ),
    ]
