# Generated by Django 4.0.4 on 2022-04-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_regularprofile_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arthubuser',
            name='type',
            field=models.CharField(choices=[('ARTIST', 'Artist'), ('REGULAR_USER', 'Regular User'), ('ART_MOD', 'Art Mod')], max_length=50),
        ),
    ]
